/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.godrandom;

import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author andresilva
 */
public class GodRandomUI extends javax.swing.JFrame {

    /**
     * Creates new form GodRandomUI
     */
    public GodRandomUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneGodRandom = new javax.swing.JTabbedPane();
        jPanelSimple = new javax.swing.JPanel();
        jPanelAddingItems = new javax.swing.JPanel();
        jTextFieldItemToAdd = new javax.swing.JTextField();
        jButtonAddItem = new javax.swing.JButton();
        jScrollPaneListOfItemsSimple = new javax.swing.JScrollPane();
        jListOfItemsSimple = new javax.swing.JList<>();
        jButtonDeleteSimple = new javax.swing.JButton();
        jButtonClearSimple = new javax.swing.JButton();
        jPanelRandomSelectionSimple = new javax.swing.JPanel();
        jButtonRandomSimple = new javax.swing.JButton();
        jTextFieldSimpleSelection = new javax.swing.JTextField();
        jPanelMultiple = new javax.swing.JPanel();
        jPanelCategoryMultiple = new javax.swing.JPanel();
        jTextFieldCategoryToAdd = new javax.swing.JTextField();
        jButtonAddCategory = new javax.swing.JButton();
        jButtonDeleteCategory = new javax.swing.JButton();
        jButtonClearCategories = new javax.swing.JButton();
        jScrollPaneCategories = new javax.swing.JScrollPane();
        jListOfCategories = new javax.swing.JList<>();
        jPanelRandomSelectionMultiple = new javax.swing.JPanel();
        jButtonStartMultiple = new javax.swing.JButton();
        jScrollPaneResultsMultiple = new javax.swing.JScrollPane();
        jListOfItemsSelectedMultiple = new javax.swing.JList<>();
        jPanelItemsMultiple = new javax.swing.JPanel();
        jButtonAddItemMultiple = new javax.swing.JButton();
        jTextFieldItemToAddMultiple = new javax.swing.JTextField();
        jScrollPaneItemsMultiple = new javax.swing.JScrollPane();
        jListOfItemsMultiple = new javax.swing.JList<>();
        jButtonDeleteItemMultiple = new javax.swing.JButton();
        jButtonClearItemsMultiple = new javax.swing.JButton();
        jComboBoxCategories = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("God Random");

        jTabbedPaneGodRandom.setToolTipText("Tab for the option 'Simple'.");

        jPanelAddingItems.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adding Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N
        jPanelAddingItems.setToolTipText("");

        jTextFieldItemToAdd.setToolTipText("Write the item here and press the \"Add item\" button to add this item to the list of items.");
        jTextFieldItemToAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemToAddActionPerformed(evt);
            }
        });

        jButtonAddItem.setText("Add");
        jButtonAddItem.setToolTipText("Adds the item to the list of items.");
        jButtonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemActionPerformed(evt);
            }
        });

        jListOfItemsSimple.setModel(modelSimple = new DefaultListModel());
        jScrollPaneListOfItemsSimple.setViewportView(jListOfItemsSimple);

        jButtonDeleteSimple.setText("Delete");
        jButtonDeleteSimple.setToolTipText("Removes the item selected from the list.");
        jButtonDeleteSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSimpleActionPerformed(evt);
            }
        });

        jButtonClearSimple.setText("Clear");
        jButtonClearSimple.setToolTipText("Removes all items from the list.");
        jButtonClearSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearSimpleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddingItemsLayout = new javax.swing.GroupLayout(jPanelAddingItems);
        jPanelAddingItems.setLayout(jPanelAddingItemsLayout);
        jPanelAddingItemsLayout.setHorizontalGroup(
            jPanelAddingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddingItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAddingItemsLayout.createSequentialGroup()
                        .addComponent(jTextFieldItemToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAddingItemsLayout.createSequentialGroup()
                        .addComponent(jScrollPaneListOfItemsSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAddingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonClearSimple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeleteSimple, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanelAddingItemsLayout.setVerticalGroup(
            jPanelAddingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddingItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldItemToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAddingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneListOfItemsSimple, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddingItemsLayout.createSequentialGroup()
                        .addComponent(jButtonDeleteSimple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClearSimple)))
                .addContainerGap())
        );

        jPanelRandomSelectionSimple.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Random Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jButtonRandomSimple.setText("Start");
        jButtonRandomSimple.setToolTipText("");
        jButtonRandomSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomSimpleActionPerformed(evt);
            }
        });

        jTextFieldSimpleSelection.setToolTipText("The item that was randomly withdrawn.");

        javax.swing.GroupLayout jPanelRandomSelectionSimpleLayout = new javax.swing.GroupLayout(jPanelRandomSelectionSimple);
        jPanelRandomSelectionSimple.setLayout(jPanelRandomSelectionSimpleLayout);
        jPanelRandomSelectionSimpleLayout.setHorizontalGroup(
            jPanelRandomSelectionSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRandomSelectionSimpleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRandomSimple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSimpleSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRandomSelectionSimpleLayout.setVerticalGroup(
            jPanelRandomSelectionSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRandomSelectionSimpleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRandomSelectionSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRandomSimple)
                    .addComponent(jTextFieldSimpleSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanelSimpleLayout = new javax.swing.GroupLayout(jPanelSimple);
        jPanelSimple.setLayout(jPanelSimpleLayout);
        jPanelSimpleLayout.setHorizontalGroup(
            jPanelSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSimpleLayout.createSequentialGroup()
                .addGroup(jPanelSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelRandomSelectionSimple, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAddingItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSimpleLayout.setVerticalGroup(
            jPanelSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimpleLayout.createSequentialGroup()
                .addComponent(jPanelAddingItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRandomSelectionSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneGodRandom.addTab("Simple", jPanelSimple);

        jPanelCategoryMultiple.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jTextFieldCategoryToAdd.setToolTipText("Write the category here and press the \"Add category\" button to add this category to the list of categories.");

        jButtonAddCategory.setText("Add");
        jButtonAddCategory.setToolTipText("Adds the category to the list of categories.");

        jButtonDeleteCategory.setText("Delete");
        jButtonDeleteCategory.setToolTipText("Removes the category selected from the list.");

        jButtonClearCategories.setText("Clear");
        jButtonClearCategories.setToolTipText("Removes all categories from the list.");

        jListOfCategories.setToolTipText("List with all categories added by now.");
        jScrollPaneCategories.setViewportView(jListOfCategories);

        javax.swing.GroupLayout jPanelCategoryMultipleLayout = new javax.swing.GroupLayout(jPanelCategoryMultiple);
        jPanelCategoryMultiple.setLayout(jPanelCategoryMultipleLayout);
        jPanelCategoryMultipleLayout.setHorizontalGroup(
            jPanelCategoryMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryMultipleLayout.createSequentialGroup()
                .addGroup(jPanelCategoryMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCategoryToAdd)
                    .addComponent(jScrollPaneCategories, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCategoryMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCategoryMultipleLayout.createSequentialGroup()
                        .addComponent(jButtonDeleteCategory)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonAddCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCategoryMultipleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonClearCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelCategoryMultipleLayout.setVerticalGroup(
            jPanelCategoryMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryMultipleLayout.createSequentialGroup()
                .addGroup(jPanelCategoryMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCategoryToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCategoryMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCategoryMultipleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonDeleteCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClearCategories))
                    .addComponent(jScrollPaneCategories)))
        );

        jPanelRandomSelectionMultiple.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Random Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jButtonStartMultiple.setText("Start");

        jListOfItemsSelectedMultiple.setToolTipText("List with all items that was randomly withdrawn.");
        jScrollPaneResultsMultiple.setViewportView(jListOfItemsSelectedMultiple);

        javax.swing.GroupLayout jPanelRandomSelectionMultipleLayout = new javax.swing.GroupLayout(jPanelRandomSelectionMultiple);
        jPanelRandomSelectionMultiple.setLayout(jPanelRandomSelectionMultipleLayout);
        jPanelRandomSelectionMultipleLayout.setHorizontalGroup(
            jPanelRandomSelectionMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRandomSelectionMultipleLayout.createSequentialGroup()
                .addComponent(jButtonStartMultiple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneResultsMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRandomSelectionMultipleLayout.setVerticalGroup(
            jPanelRandomSelectionMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRandomSelectionMultipleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonStartMultiple)
                .addContainerGap(65, Short.MAX_VALUE))
            .addComponent(jScrollPaneResultsMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanelItemsMultiple.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jButtonAddItemMultiple.setText("Add");
        jButtonAddItemMultiple.setToolTipText("Adds the item to the list of items of selected category.");

        jTextFieldItemToAddMultiple.setToolTipText("Write the item here and press the \"Add item\" button to add this item to the list of items.");

        jListOfItemsMultiple.setToolTipText("List with all items added by now.");
        jScrollPaneItemsMultiple.setViewportView(jListOfItemsMultiple);

        jButtonDeleteItemMultiple.setText("Delete");
        jButtonDeleteItemMultiple.setToolTipText("Removes the item selected from the list.");

        jButtonClearItemsMultiple.setText("Clear");
        jButtonClearItemsMultiple.setToolTipText("Removes all items from the list.");

        jComboBoxCategories.setToolTipText("Select a category where the ");

        javax.swing.GroupLayout jPanelItemsMultipleLayout = new javax.swing.GroupLayout(jPanelItemsMultiple);
        jPanelItemsMultiple.setLayout(jPanelItemsMultipleLayout);
        jPanelItemsMultipleLayout.setHorizontalGroup(
            jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItemsMultipleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneItemsMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanelItemsMultipleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextFieldItemToAddMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxCategories, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAddItemMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDeleteItemMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClearItemsMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );
        jPanelItemsMultipleLayout.setVerticalGroup(
            jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemsMultipleLayout.createSequentialGroup()
                .addComponent(jTextFieldItemToAddMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddItemMultiple))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItemsMultipleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonDeleteItemMultiple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClearItemsMultiple))
                    .addComponent(jScrollPaneItemsMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelMultipleLayout = new javax.swing.GroupLayout(jPanelMultiple);
        jPanelMultiple.setLayout(jPanelMultipleLayout);
        jPanelMultipleLayout.setHorizontalGroup(
            jPanelMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMultipleLayout.createSequentialGroup()
                .addGroup(jPanelMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelRandomSelectionMultiple, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelMultipleLayout.createSequentialGroup()
                        .addComponent(jPanelCategoryMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelItemsMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelMultipleLayout.setVerticalGroup(
            jPanelMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMultipleLayout.createSequentialGroup()
                .addGroup(jPanelMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCategoryMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelItemsMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRandomSelectionMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneGodRandom.addTab("Multiple", jPanelMultiple);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneGodRandom)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneGodRandom)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemActionPerformed
        addItems(jTextFieldItemToAdd);
    }//GEN-LAST:event_jButtonAddItemActionPerformed

    private void jButtonDeleteSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSimpleActionPerformed
        int[] positions = jListOfItemsSimple.getSelectedIndices();
        int posLength;
        
        if ((posLength = positions.length) > 0) {
            for (int i=posLength-1; i>=0; i--) {
                modelSimple.remove(positions[i]);
            }
        }
    }//GEN-LAST:event_jButtonDeleteSimpleActionPerformed

    private void jButtonClearSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearSimpleActionPerformed
        modelSimple.removeAllElements();
    }//GEN-LAST:event_jButtonClearSimpleActionPerformed

    private void jButtonRandomSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandomSimpleActionPerformed
        //String[] res = new String[1];
        //res = 
        jTextFieldSimpleSelection.setText(runGodRandom(modelSimple, true)[0]);
    }//GEN-LAST:event_jButtonRandomSimpleActionPerformed

    private void jTextFieldItemToAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemToAddActionPerformed
        addItems(jTextFieldItemToAdd);
    }//GEN-LAST:event_jTextFieldItemToAddActionPerformed
    
    private void addItems(javax.swing.JTextField component) {
        String item = component.getText();
        
        modelSimple.addElement(item);
        jTextFieldItemToAdd.setText("");
    }
    
    private String[] runGodRandom(DefaultListModel model, boolean simple) {
        String[] items = new String[model.getSize()];
        
        for (int i=0; i<model.getSize(); i++) {
            items[i] = (String) model.get(i);
        }
        
        return selectRandomly(items, simple);
    }
    
    private String[] selectRandomly(String[] list, boolean simple) {
        Random random = new Random();
        
        if (simple) { 
            String[] res = {list[random.nextInt(list.length)]}; 
            
            return res; 
        }
        
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GodRandomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GodRandomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GodRandomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GodRandomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GodRandomUI().setVisible(true);
            }
        });
    }

    private DefaultListModel modelSimple;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCategory;
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonAddItemMultiple;
    private javax.swing.JButton jButtonClearCategories;
    private javax.swing.JButton jButtonClearItemsMultiple;
    private javax.swing.JButton jButtonClearSimple;
    private javax.swing.JButton jButtonDeleteCategory;
    private javax.swing.JButton jButtonDeleteItemMultiple;
    private javax.swing.JButton jButtonDeleteSimple;
    private javax.swing.JButton jButtonRandomSimple;
    private javax.swing.JButton jButtonStartMultiple;
    private javax.swing.JComboBox<String> jComboBoxCategories;
    private javax.swing.JList<String> jListOfCategories;
    private javax.swing.JList<String> jListOfItemsMultiple;
    private javax.swing.JList<String> jListOfItemsSelectedMultiple;
    private javax.swing.JList<String> jListOfItemsSimple;
    private javax.swing.JPanel jPanelAddingItems;
    private javax.swing.JPanel jPanelCategoryMultiple;
    private javax.swing.JPanel jPanelItemsMultiple;
    private javax.swing.JPanel jPanelMultiple;
    private javax.swing.JPanel jPanelRandomSelectionMultiple;
    private javax.swing.JPanel jPanelRandomSelectionSimple;
    private javax.swing.JPanel jPanelSimple;
    private javax.swing.JScrollPane jScrollPaneCategories;
    private javax.swing.JScrollPane jScrollPaneItemsMultiple;
    private javax.swing.JScrollPane jScrollPaneListOfItemsSimple;
    private javax.swing.JScrollPane jScrollPaneResultsMultiple;
    private javax.swing.JTabbedPane jTabbedPaneGodRandom;
    private javax.swing.JTextField jTextFieldCategoryToAdd;
    private javax.swing.JTextField jTextFieldItemToAdd;
    private javax.swing.JTextField jTextFieldItemToAddMultiple;
    private javax.swing.JTextField jTextFieldSimpleSelection;
    // End of variables declaration//GEN-END:variables
}
