/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.godrandom;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author andresilva
 */
public class GodRandomUI extends javax.swing.JFrame {

    /**
     * Creates new form GodRandomUI
     */
    public GodRandomUI() {
        initComponents();
        multipleItems = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneGodRandom = new javax.swing.JTabbedPane();
        jPanelSimple = new javax.swing.JPanel();
        jPanelAddingItems = new javax.swing.JPanel();
        jTextFieldItemToAdd = new javax.swing.JTextField();
        jButtonAddItem = new javax.swing.JButton();
        jScrollPaneListOfItemsSimple = new javax.swing.JScrollPane();
        jListOfItemsSimple = new javax.swing.JList<>();
        jButtonDeleteSimple = new javax.swing.JButton();
        jButtonClearSimple = new javax.swing.JButton();
        jPanelRandomSelectionSimple = new javax.swing.JPanel();
        jButtonRandomSimple = new javax.swing.JButton();
        jTextFieldSimpleSelection = new javax.swing.JTextField();
        jPanelMultiple = new javax.swing.JPanel();
        jPanelCategoryMultiple = new javax.swing.JPanel();
        jTextFieldCategoryToAdd = new javax.swing.JTextField();
        jButtonAddCategory = new javax.swing.JButton();
        jButtonDeleteCategory = new javax.swing.JButton();
        jButtonClearCategories = new javax.swing.JButton();
        jScrollPaneCategories = new javax.swing.JScrollPane();
        jListOfCategories = new javax.swing.JList<>();
        jPanelRandomSelectionMultiple = new javax.swing.JPanel();
        jButtonStartMultiple = new javax.swing.JButton();
        jScrollPaneResultsMultiple = new javax.swing.JScrollPane();
        jListOfItemsSelectedMultiple = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCategoriesOrder = new javax.swing.JList<>();
        jLabelCategoriesOrder = new javax.swing.JLabel();
        jLabelItemsSelectedMultiple = new javax.swing.JLabel();
        jPanelItemsMultiple = new javax.swing.JPanel();
        jButtonAddItemMultiple = new javax.swing.JButton();
        jTextFieldItemToAddMultiple = new javax.swing.JTextField();
        jScrollPaneItemsMultiple = new javax.swing.JScrollPane();
        jListOfItemsMultiple = new javax.swing.JList<>();
        jButtonDeleteItemMultiple = new javax.swing.JButton();
        jButtonClearAllMultiple = new javax.swing.JButton();
        jComboBoxCategories = new javax.swing.JComboBox<>();
        jButtonClearItemsCategoryMultiple = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("God Random");

        jTabbedPaneGodRandom.setToolTipText("Tab for the option 'Simple'.");

        jPanelAddingItems.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adding Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N
        jPanelAddingItems.setToolTipText("");

        jTextFieldItemToAdd.setToolTipText("Write the item here and press the \"Add item\" button to add this item to the list of items.");
        jTextFieldItemToAdd.setName("jTextFieldItemToAdd"); // NOI18N
        jTextFieldItemToAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemToAddActionPerformed(evt);
            }
        });

        jButtonAddItem.setText("Add");
        jButtonAddItem.setToolTipText("Adds the item to the list of items.");
        jButtonAddItem.setName(""); // NOI18N
        jButtonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemActionPerformed(evt);
            }
        });

        jListOfItemsSimple.setModel(modelSimple = new DefaultListModel());
        jListOfItemsSimple.setName("jListOfItemsSimple"); // NOI18N
        jScrollPaneListOfItemsSimple.setViewportView(jListOfItemsSimple);

        jButtonDeleteSimple.setText("Delete");
        jButtonDeleteSimple.setToolTipText("Removes the item selected from the list.");
        jButtonDeleteSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteSimpleActionPerformed(evt);
            }
        });

        jButtonClearSimple.setText("Clear");
        jButtonClearSimple.setToolTipText("Removes all items from the list.");
        jButtonClearSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearSimpleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddingItemsLayout = new javax.swing.GroupLayout(jPanelAddingItems);
        jPanelAddingItems.setLayout(jPanelAddingItemsLayout);
        jPanelAddingItemsLayout.setHorizontalGroup(
            jPanelAddingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddingItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAddingItemsLayout.createSequentialGroup()
                        .addComponent(jTextFieldItemToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAddingItemsLayout.createSequentialGroup()
                        .addComponent(jScrollPaneListOfItemsSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAddingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonClearSimple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeleteSimple, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        jPanelAddingItemsLayout.setVerticalGroup(
            jPanelAddingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddingItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAddingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldItemToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAddingItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneListOfItemsSimple, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddingItemsLayout.createSequentialGroup()
                        .addComponent(jButtonDeleteSimple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClearSimple)))
                .addContainerGap())
        );

        jPanelRandomSelectionSimple.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Random Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jButtonRandomSimple.setText("Start");
        jButtonRandomSimple.setToolTipText("");
        jButtonRandomSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomSimpleActionPerformed(evt);
            }
        });

        jTextFieldSimpleSelection.setToolTipText("The item that was randomly withdrawn.");

        javax.swing.GroupLayout jPanelRandomSelectionSimpleLayout = new javax.swing.GroupLayout(jPanelRandomSelectionSimple);
        jPanelRandomSelectionSimple.setLayout(jPanelRandomSelectionSimpleLayout);
        jPanelRandomSelectionSimpleLayout.setHorizontalGroup(
            jPanelRandomSelectionSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRandomSelectionSimpleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRandomSimple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSimpleSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRandomSelectionSimpleLayout.setVerticalGroup(
            jPanelRandomSelectionSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRandomSelectionSimpleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelRandomSelectionSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRandomSimple)
                    .addComponent(jTextFieldSimpleSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanelSimpleLayout = new javax.swing.GroupLayout(jPanelSimple);
        jPanelSimple.setLayout(jPanelSimpleLayout);
        jPanelSimpleLayout.setHorizontalGroup(
            jPanelSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSimpleLayout.createSequentialGroup()
                .addGroup(jPanelSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelRandomSelectionSimple, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelAddingItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSimpleLayout.setVerticalGroup(
            jPanelSimpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSimpleLayout.createSequentialGroup()
                .addComponent(jPanelAddingItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRandomSelectionSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneGodRandom.addTab("Simple", jPanelSimple);

        jPanelCategoryMultiple.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jTextFieldCategoryToAdd.setToolTipText("Write the category here and press the \"Add category\" button to add this category to the list of categories.");
        jTextFieldCategoryToAdd.setName("jTextFieldCategoryToAdd"); // NOI18N
        jTextFieldCategoryToAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCategoryToAddActionPerformed(evt);
            }
        });

        jButtonAddCategory.setText("Add");
        jButtonAddCategory.setToolTipText("Adds the category to the list of categories.");
        jButtonAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCategoryActionPerformed(evt);
            }
        });

        jButtonDeleteCategory.setText("Delete");
        jButtonDeleteCategory.setToolTipText("Removes the category selected from the list.");
        jButtonDeleteCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCategoryActionPerformed(evt);
            }
        });

        jButtonClearCategories.setText("Clear");
        jButtonClearCategories.setToolTipText("Removes all categories from the list.");
        jButtonClearCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearCategoriesActionPerformed(evt);
            }
        });

        jListOfCategories.setModel(modelMultipleCategory = new DefaultListModel());
        jListOfCategories.setToolTipText("List with all categories added by now.");
        jListOfCategories.setName("jListOfCategories"); // NOI18N
        jScrollPaneCategories.setViewportView(jListOfCategories);

        javax.swing.GroupLayout jPanelCategoryMultipleLayout = new javax.swing.GroupLayout(jPanelCategoryMultiple);
        jPanelCategoryMultiple.setLayout(jPanelCategoryMultipleLayout);
        jPanelCategoryMultipleLayout.setHorizontalGroup(
            jPanelCategoryMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryMultipleLayout.createSequentialGroup()
                .addGroup(jPanelCategoryMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCategoryToAdd)
                    .addComponent(jScrollPaneCategories, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCategoryMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCategoryMultipleLayout.createSequentialGroup()
                        .addComponent(jButtonDeleteCategory)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonAddCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCategoryMultipleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonClearCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelCategoryMultipleLayout.setVerticalGroup(
            jPanelCategoryMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryMultipleLayout.createSequentialGroup()
                .addGroup(jPanelCategoryMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCategoryToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCategoryMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCategoryMultipleLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonDeleteCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClearCategories))
                    .addComponent(jScrollPaneCategories)))
        );

        jPanelRandomSelectionMultiple.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Random Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jButtonStartMultiple.setText("Start");
        jButtonStartMultiple.setToolTipText("<html>For multiple items selection the run of God Random  is split in two parts:\n    <ul>\n        <li>the first one serves to obtain the order of the categories;</li>\n        <li>the second part will select (randomly) an item from every category,<br>respecting the order obtained from the previous running.</li>\n    </ul>\n</html>");
        jButtonStartMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartMultipleActionPerformed(evt);
            }
        });

        jListOfItemsSelectedMultiple.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListOfItemsSelectedMultiple.setToolTipText("Final list with all items that was randomly withdrawn (each item corresponds to a category).");
        jListOfItemsSelectedMultiple.setSelectionModel(new DisabledItemSelectionModel());
        jScrollPaneResultsMultiple.setViewportView(jListOfItemsSelectedMultiple);

        jListCategoriesOrder.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListCategoriesOrder.setToolTipText("<html>\nList with all ordered categories for next step, which it consists to run the God Random<br>for every category to select an item from it and add to the final items list.");
        jListCategoriesOrder.setSelectionModel(new DisabledItemSelectionModel());
        jScrollPane1.setViewportView(jListCategoriesOrder);

        jLabelCategoriesOrder.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelCategoriesOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCategoriesOrder.setLabelFor(jListCategoriesOrder);
        jLabelCategoriesOrder.setText("Order of the categories");

        jLabelItemsSelectedMultiple.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabelItemsSelectedMultiple.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelItemsSelectedMultiple.setLabelFor(jListOfItemsSelectedMultiple);
        jLabelItemsSelectedMultiple.setText("Final list");

        javax.swing.GroupLayout jPanelRandomSelectionMultipleLayout = new javax.swing.GroupLayout(jPanelRandomSelectionMultiple);
        jPanelRandomSelectionMultiple.setLayout(jPanelRandomSelectionMultipleLayout);
        jPanelRandomSelectionMultipleLayout.setHorizontalGroup(
            jPanelRandomSelectionMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRandomSelectionMultipleLayout.createSequentialGroup()
                .addComponent(jButtonStartMultiple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRandomSelectionMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCategoriesOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRandomSelectionMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelItemsSelectedMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneResultsMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelRandomSelectionMultipleLayout.setVerticalGroup(
            jPanelRandomSelectionMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRandomSelectionMultipleLayout.createSequentialGroup()
                .addGroup(jPanelRandomSelectionMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRandomSelectionMultipleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelRandomSelectionMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCategoriesOrder)
                            .addComponent(jLabelItemsSelectedMultiple)))
                    .addGroup(jPanelRandomSelectionMultipleLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelRandomSelectionMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonStartMultiple)
                            .addGroup(jPanelRandomSelectionMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPaneResultsMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelItemsMultiple.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        jButtonAddItemMultiple.setText("Add");
        jButtonAddItemMultiple.setToolTipText("Adds the item to the list of items of selected category.");
        jButtonAddItemMultiple.setEnabled(false);
        jButtonAddItemMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemMultipleActionPerformed(evt);
            }
        });

        jTextFieldItemToAddMultiple.setToolTipText("Write the item here and press the \"Add item\" button to add this item to the list of items.");
        jTextFieldItemToAddMultiple.setName("jTextFieldItemToAddMultiple"); // NOI18N
        jTextFieldItemToAddMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemToAddMultipleActionPerformed(evt);
            }
        });

        jListOfItemsMultiple.setModel(modelMultipleItem = new DefaultListModel());
        jListOfItemsMultiple.setToolTipText("List with all items added by now.");
        jListOfItemsMultiple.setName("jListOfItemsMultiple"); // NOI18N
        jScrollPaneItemsMultiple.setViewportView(jListOfItemsMultiple);

        jButtonDeleteItemMultiple.setText("Delete");
        jButtonDeleteItemMultiple.setToolTipText("Removes the item selected from the list.");
        jButtonDeleteItemMultiple.setEnabled(false);
        jButtonDeleteItemMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteItemMultipleActionPerformed(evt);
            }
        });

        jButtonClearAllMultiple.setText("Clear all");
        jButtonClearAllMultiple.setToolTipText("Removes all items from the list.");
        jButtonClearAllMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearAllMultipleActionPerformed(evt);
            }
        });

        jComboBoxCategories.setMaximumRowCount(20);
        jComboBoxCategories.setModel(modelCombo = new DefaultComboBoxModel());
        jComboBoxCategories.setToolTipText("Select a category where the ");
        jComboBoxCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriesActionPerformed(evt);
            }
        });

        jButtonClearItemsCategoryMultiple.setText("Clear category");
        jButtonClearItemsCategoryMultiple.setToolTipText("Removes all items associated with the selected category.");
        jButtonClearItemsCategoryMultiple.setEnabled(false);
        jButtonClearItemsCategoryMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearItemsCategoryMultipleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelItemsMultipleLayout = new javax.swing.GroupLayout(jPanelItemsMultiple);
        jPanelItemsMultiple.setLayout(jPanelItemsMultipleLayout);
        jPanelItemsMultipleLayout.setHorizontalGroup(
            jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemsMultipleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItemsMultipleLayout.createSequentialGroup()
                        .addGroup(jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCategories, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPaneItemsMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonClearItemsCategoryMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClearAllMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDeleteItemMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAddItemMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addGroup(jPanelItemsMultipleLayout.createSequentialGroup()
                        .addComponent(jTextFieldItemToAddMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelItemsMultipleLayout.setVerticalGroup(
            jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemsMultipleLayout.createSequentialGroup()
                .addComponent(jTextFieldItemToAddMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddItemMultiple))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItemsMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItemsMultipleLayout.createSequentialGroup()
                        .addComponent(jButtonDeleteItemMultiple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClearItemsCategoryMultiple)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClearAllMultiple))
                    .addComponent(jScrollPaneItemsMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanelMultipleLayout = new javax.swing.GroupLayout(jPanelMultiple);
        jPanelMultiple.setLayout(jPanelMultipleLayout);
        jPanelMultipleLayout.setHorizontalGroup(
            jPanelMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMultipleLayout.createSequentialGroup()
                .addGroup(jPanelMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMultipleLayout.createSequentialGroup()
                        .addComponent(jPanelCategoryMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelItemsMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelRandomSelectionMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMultipleLayout.setVerticalGroup(
            jPanelMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMultipleLayout.createSequentialGroup()
                .addGroup(jPanelMultipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCategoryMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelItemsMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRandomSelectionMultiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneGodRandom.addTab("Multiple", jPanelMultiple);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneGodRandom)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneGodRandom)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemActionPerformed
        addItems(jTextFieldItemToAdd, modelSimple);
    }//GEN-LAST:event_jButtonAddItemActionPerformed

    private void jButtonDeleteSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteSimpleActionPerformed
        removeItems(jListOfItemsSimple, modelSimple);
    }//GEN-LAST:event_jButtonDeleteSimpleActionPerformed

    private void jButtonClearSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearSimpleActionPerformed
        modelSimple.removeAllElements();
    }//GEN-LAST:event_jButtonClearSimpleActionPerformed

    private void jButtonRandomSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandomSimpleActionPerformed
        jTextFieldSimpleSelection.setText(runGodRandom(modelSimple, true)[0]);
    }//GEN-LAST:event_jButtonRandomSimpleActionPerformed

    private void jTextFieldItemToAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemToAddActionPerformed
        addItems(jTextFieldItemToAdd, modelSimple);
    }//GEN-LAST:event_jTextFieldItemToAddActionPerformed

    private void jTextFieldCategoryToAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCategoryToAddActionPerformed
        addItems(jTextFieldCategoryToAdd, modelMultipleCategory);
    }//GEN-LAST:event_jTextFieldCategoryToAddActionPerformed

    private void jButtonAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCategoryActionPerformed
        addItems(jTextFieldCategoryToAdd, modelMultipleCategory);
    }//GEN-LAST:event_jButtonAddCategoryActionPerformed

    private void jButtonDeleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCategoryActionPerformed
        removeItems(jListOfCategories, modelMultipleCategory);
    }//GEN-LAST:event_jButtonDeleteCategoryActionPerformed

    private void jButtonClearCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearCategoriesActionPerformed
        modelMultipleCategory.removeAllElements();
        modelCombo.removeAllElements();
    }//GEN-LAST:event_jButtonClearCategoriesActionPerformed

    private void jComboBoxCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriesActionPerformed
        if (jComboBoxCategories.getSelectedIndex() != -1) {
            jButtonAddItemMultiple.setEnabled(true);
            jButtonDeleteItemMultiple.setEnabled(true);
            jButtonClearItemsCategoryMultiple.setEnabled(true);
            
            if (!multipleItems.isEmpty()) {
                modelMultipleItem.removeAllElements();
                
                ArrayList<String> categoryValues;
                if ((categoryValues = multipleItems.
                        get((String) jComboBoxCategories.getSelectedItem())) != null) {
                    for (String value: categoryValues) {
                        modelMultipleItem.addElement(value);
                    }
                }
            }
        }
    }//GEN-LAST:event_jComboBoxCategoriesActionPerformed

    private void jTextFieldItemToAddMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemToAddMultipleActionPerformed
        if (jComboBoxCategories.getSelectedIndex() != -1) {
            addItems(jTextFieldItemToAddMultiple, modelMultipleItem);
        }
        else {
            JOptionPane.showMessageDialog(new JFrame(), "Please, select the category"
                    + " where the item will be added.", "Category not found", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jTextFieldItemToAddMultipleActionPerformed

    private void jButtonAddItemMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemMultipleActionPerformed
        addItems(jTextFieldItemToAddMultiple, modelMultipleItem);
    }//GEN-LAST:event_jButtonAddItemMultipleActionPerformed

    private void jButtonDeleteItemMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteItemMultipleActionPerformed
        removeItems(jListOfItemsMultiple, modelMultipleItem);
    }//GEN-LAST:event_jButtonDeleteItemMultipleActionPerformed

    private void jButtonClearItemsCategoryMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearItemsCategoryMultipleActionPerformed
        multipleItems.remove((String) jComboBoxCategories.getSelectedItem());
        modelMultipleItem.removeAllElements();
    }//GEN-LAST:event_jButtonClearItemsCategoryMultipleActionPerformed

    private void jButtonClearAllMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearAllMultipleActionPerformed
        multipleItems.clear();
        modelMultipleItem.removeAllElements();
    }//GEN-LAST:event_jButtonClearAllMultipleActionPerformed

    private void jButtonStartMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartMultipleActionPerformed
        int sizeOfList = modelMultipleCategory.size();
        
        String[] categoriesSorted = Arrays.copyOf(modelMultipleCategory.toArray(), 
                sizeOfList, String[].class);
        Collections.shuffle(Arrays.asList(categoriesSorted));
        jListCategoriesOrder.setListData(categoriesSorted);
        
        String[] finalList = selectRandomly(categoriesSorted, false);
        jListOfItemsSelectedMultiple.setListData(finalList);
    }//GEN-LAST:event_jButtonStartMultipleActionPerformed
    
    private void addItems(javax.swing.JTextField component, DefaultListModel model) {
        String item = component.getText();
        
        // Simple addition
        model.addElement(item);
        
        // Addition of a new category
        if (component.getName().equals("jTextFieldCategoryToAdd")) {
            modelCombo.addElement(item);
        }
        
        // Addition of an item to the selected category
        else if (component.getName().equals("jTextFieldItemToAddMultiple")) {
            ArrayList<String> multipleValues = new ArrayList<>();
            
            if (multipleItems.get((String) jComboBoxCategories.getSelectedItem()) != null) {
                multipleValues.addAll(multipleItems.get((String) jComboBoxCategories.getSelectedItem()));
            }
            multipleValues.add(item);
            multipleItems.put((String) jComboBoxCategories.getSelectedItem(), multipleValues);
        }
        
        component.setText("");
    }
    
    private void removeItems(JList list, DefaultListModel model) {
        int[] positions = list.getSelectedIndices();
        int posLength;
        
        if ((posLength = positions.length) > 0) {
            for (int i=posLength-1; i>=0; i--) {
                model.remove(positions[i]);
                if (list.getName().equals("jListOfCategories")) {
                    modelCombo.removeElementAt(positions[i]);
                }
                else if (list.getName().equals("jListOfItemsMultiple")) {
                    ArrayList<String> newValues = new ArrayList<>();
                    newValues.addAll(multipleItems.get((String) jComboBoxCategories.getSelectedItem()));
                    newValues.remove(positions[i]);
                    multipleItems.replace((String) jComboBoxCategories.getSelectedItem(), newValues);
                }
            }
        }
    }
    
    private String[] runGodRandom(DefaultListModel model, boolean isSimple) {
        String[] items = new String[model.getSize()];
        
        for (int i=0; i<model.getSize(); i++) {
            items[i] = (String) model.get(i);
        }
        
        return selectRandomly(items, isSimple);
    }
    
    private String[] selectRandomly(String[] list, boolean isSimple) {
        Random random = new Random();
        
        if (isSimple) { 
            String[] res = {list[random.nextInt(list.length)]};     
            return res; 
        }
        
        int sizeOfList = list.length;
        int i = 0;
        String[] res = new String[sizeOfList];
        
        for (String category: list) {
            String[] itemsOfCategory = Arrays.copyOf(multipleItems.get(category).toArray(), 
                multipleItems.get(category).size(), String[].class);
            String aux = selectRandomly(itemsOfCategory, true)[0];
            res[i++] = aux;
        }
        
        return res;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GodRandomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GodRandomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GodRandomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GodRandomUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GodRandomUI().setVisible(true);
            }
        });
    }

    private DefaultListModel modelSimple;
    private DefaultListModel modelMultipleCategory;
    private DefaultListModel modelMultipleItem;
    private DefaultComboBoxModel modelCombo;
    private HashMap<String, ArrayList<String>> multipleItems;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCategory;
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonAddItemMultiple;
    private javax.swing.JButton jButtonClearAllMultiple;
    private javax.swing.JButton jButtonClearCategories;
    private javax.swing.JButton jButtonClearItemsCategoryMultiple;
    private javax.swing.JButton jButtonClearSimple;
    private javax.swing.JButton jButtonDeleteCategory;
    private javax.swing.JButton jButtonDeleteItemMultiple;
    private javax.swing.JButton jButtonDeleteSimple;
    private javax.swing.JButton jButtonRandomSimple;
    private javax.swing.JButton jButtonStartMultiple;
    private javax.swing.JComboBox<String> jComboBoxCategories;
    private javax.swing.JLabel jLabelCategoriesOrder;
    private javax.swing.JLabel jLabelItemsSelectedMultiple;
    private javax.swing.JList<String> jListCategoriesOrder;
    private javax.swing.JList<String> jListOfCategories;
    private javax.swing.JList<String> jListOfItemsMultiple;
    private javax.swing.JList<String> jListOfItemsSelectedMultiple;
    private javax.swing.JList<String> jListOfItemsSimple;
    private javax.swing.JPanel jPanelAddingItems;
    private javax.swing.JPanel jPanelCategoryMultiple;
    private javax.swing.JPanel jPanelItemsMultiple;
    private javax.swing.JPanel jPanelMultiple;
    private javax.swing.JPanel jPanelRandomSelectionMultiple;
    private javax.swing.JPanel jPanelRandomSelectionSimple;
    private javax.swing.JPanel jPanelSimple;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneCategories;
    private javax.swing.JScrollPane jScrollPaneItemsMultiple;
    private javax.swing.JScrollPane jScrollPaneListOfItemsSimple;
    private javax.swing.JScrollPane jScrollPaneResultsMultiple;
    private javax.swing.JTabbedPane jTabbedPaneGodRandom;
    private javax.swing.JTextField jTextFieldCategoryToAdd;
    private javax.swing.JTextField jTextFieldItemToAdd;
    private javax.swing.JTextField jTextFieldItemToAddMultiple;
    private javax.swing.JTextField jTextFieldSimpleSelection;
    // End of variables declaration//GEN-END:variables
}
